### ISSUE TITLE
Design choice w.r.t. the DAM MLM training

### ISSUE THREAD

**Issue by zhichaoxu-shufe** [jingtaozhan/disentangled-retriever#10]
Hi Jingtao:

I wonder what is the **max_seq_len** hyparameter you use when doing MLM on target domain dataset? 

In the huggingface example they use a **block_size**=128, just curious why you did not use their method directly.

Also I am interested in the effect of leaving out [CLS] and [SEP] in preparing the MLM dataloader, does it make a huge difference if you do not remove these two tokens?

**Comment by jingtaozhan** [comment]
Hi Zhichao,

I did not tune max_seq_len and just set it to 100. I'm not aware of the default parameter setting of the huggingface example.

[cls] and [sep] are not left out. They are added to the input with [`prepare_for_model' function](https://github.com/jingtaozhan/disentangled-retriever/blob/dcba95c7a220740ecc58f4ace55144159dc628ee/src/disentangled_retriever/dense/adapt/run_adapt_with_mlm.py#L62)

**Comment by zhichaoxu-shufe** [comment]
thanks for the instant reply! 

Setting **max_seq_len** to 100 completely makes sense.

But (correct me if I am wrong) in **__getitem__** from CorpusDataset you seem to create one training instance for one passage and leave out the rest parts of passage if longer than 100, will this be problematic? 

In the huggingface example they first concatenate all passages, then separate the long string into smaller blocks and use them as into to **trainer** class.

**Comment by jingtaozhan** [comment]
[This line](https://github.com/jingtaozhan/disentangled-retriever/blob/dcba95c7a220740ecc58f4ace55144159dc628ee/src/disentangled_retriever/dense/adapt/run_adapt_with_mlm.py#L54) will ignore the max-length limitation and tokenize the entire passage. The tokenized ids are cached.
Then [this line](https://github.com/jingtaozhan/disentangled-retriever/blob/dcba95c7a220740ecc58f4ace55144159dc628ee/src/disentangled_retriever/dense/adapt/run_adapt_with_mlm.py#L58) will select a random span with a maximum length of 100.

**Comment by zhichaoxu-shufe** [comment]
thanks a lot! that answers my question
